version: '3.1'

volumes:
  db_vol:

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=budgetify
      - POSTGRES_PASSWORD=budgetify
    volumes:
      - db_vol:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  dbtest:
    image: postgres:13
    environment:
      - POSTGRES_DB=budgetifytest
      - POSTGRES_PASSWORD=budgetify
    ports:
      - '5433:5432'
